### ISSUE TITLE
serverless workflow helloworld url not found

### ISSUE THREAD

**Issue by gonzalezcaf** [kiegroup/kogito-docs#103]
Hi, in the webpage:
https://kiegroup.github.io/kogito-docs/serverlessworkflow/main/getting-started/create-your-first-workflow-service.html
the url: https://github.com/kiegroup/kogito-examples/tree/main/serverless-workflow-examples/serverless-workflow-hello-world
is HTTP 404 Not Found

**Comment by radtriste** [comment]
@gonzalezcaf Thanks for reporting. will correct that.

**Comment by radtriste** [comment]
@hbelmiro `serverless-workflow-hello-world` does not exist on main. I see that you updated URLs some time ago: https://github.com/kiegroup/kogito-docs/pull/27/files#diff-0a60c1221612ee9f6cba27c0d6e74be0010e4fcd698818a997b3cea65d8b34bcL10
Would you have this example on your fork ?
cc @ricardozanini

**Comment by hbelmiro** [comment]
@radtriste Yes. I have an open PR to add this example.
https://github.com/kiegroup/kogito-examples/pull/1266
@ricardozanini I think we're ready to merge this PR.

**Comment by radtriste** [comment]
issue merged
